// Code generated by protoc-gen-go.
// source: common/server/alarm/alarm.proto
// DO NOT EDIT!

/*
Package alarm_message is a generated protocol buffer package.

It is generated from these files:
	common/server/alarm/alarm.proto

It has these top-level messages:
	Alarm
	SyncTime
*/
package alarm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Alarm struct {
	Hours            *uint32 `protobuf:"varint,1,req,name=hours" json:"hours,omitempty"`
	Minutes          *uint32 `protobuf:"varint,2,req,name=minutes" json:"minutes,omitempty"`
	Repetiton        *bool   `protobuf:"varint,3,req,name=repetiton" json:"repetiton,omitempty"`
	WeekInfo         *uint32 `protobuf:"varint,4,req,name=week_info,json=weekInfo" json:"week_info,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Alarm) Reset()                    { *m = Alarm{} }
func (m *Alarm) String() string            { return proto.CompactTextString(m) }
func (*Alarm) ProtoMessage()               {}
func (*Alarm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Alarm) GetHours() uint32 {
	if m != nil && m.Hours != nil {
		return *m.Hours
	}
	return 0
}

func (m *Alarm) GetMinutes() uint32 {
	if m != nil && m.Minutes != nil {
		return *m.Minutes
	}
	return 0
}

func (m *Alarm) GetRepetiton() bool {
	if m != nil && m.Repetiton != nil {
		return *m.Repetiton
	}
	return false
}

func (m *Alarm) GetWeekInfo() uint32 {
	if m != nil && m.WeekInfo != nil {
		return *m.WeekInfo
	}
	return 0
}

type SyncTime struct {
	Year             *uint32 `protobuf:"varint,1,req,name=year" json:"year,omitempty"`
	Month            *uint32 `protobuf:"varint,2,req,name=month" json:"month,omitempty"`
	Day              *uint32 `protobuf:"varint,3,req,name=day" json:"day,omitempty"`
	Weekday          *uint32 `protobuf:"varint,4,req,name=weekday" json:"weekday,omitempty"`
	Hours            *uint32 `protobuf:"varint,5,req,name=hours" json:"hours,omitempty"`
	Minutes          *uint32 `protobuf:"varint,6,req,name=minutes" json:"minutes,omitempty"`
	Seconds          *uint32 `protobuf:"varint,7,req,name=seconds" json:"seconds,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SyncTime) Reset()                    { *m = SyncTime{} }
func (m *SyncTime) String() string            { return proto.CompactTextString(m) }
func (*SyncTime) ProtoMessage()               {}
func (*SyncTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SyncTime) GetYear() uint32 {
	if m != nil && m.Year != nil {
		return *m.Year
	}
	return 0
}

func (m *SyncTime) GetMonth() uint32 {
	if m != nil && m.Month != nil {
		return *m.Month
	}
	return 0
}

func (m *SyncTime) GetDay() uint32 {
	if m != nil && m.Day != nil {
		return *m.Day
	}
	return 0
}

func (m *SyncTime) GetWeekday() uint32 {
	if m != nil && m.Weekday != nil {
		return *m.Weekday
	}
	return 0
}

func (m *SyncTime) GetHours() uint32 {
	if m != nil && m.Hours != nil {
		return *m.Hours
	}
	return 0
}

func (m *SyncTime) GetMinutes() uint32 {
	if m != nil && m.Minutes != nil {
		return *m.Minutes
	}
	return 0
}

func (m *SyncTime) GetSeconds() uint32 {
	if m != nil && m.Seconds != nil {
		return *m.Seconds
	}
	return 0
}

func init() {
	proto.RegisterType((*Alarm)(nil), "alarm.message.Alarm")
	proto.RegisterType((*SyncTime)(nil), "alarm.message.SyncTime")
}

func init() { proto.RegisterFile("common/server/alarm/alarm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x69, 0xda, 0x75, 0xb7, 0x03, 0x0b, 0x32, 0x78, 0x08, 0x28, 0x58, 0x7a, 0xea, 0xc9,
	0x3e, 0x83, 0x9e, 0xf4, 0xba, 0x7a, 0x97, 0xb0, 0x9d, 0xda, 0x45, 0x33, 0x53, 0x26, 0xa9, 0xb2,
	0xaf, 0xe4, 0x53, 0x4a, 0x36, 0x5b, 0x16, 0x0f, 0xbd, 0x84, 0xf9, 0xbe, 0x90, 0xfc, 0xf3, 0xc3,
	0x7d, 0x2b, 0xde, 0x0b, 0x6f, 0x03, 0xe9, 0x37, 0xe9, 0xd6, 0x7d, 0x39, 0xf5, 0xf9, 0x7c, 0x38,
	0xaa, 0x44, 0xc1, 0x3a, 0x83, 0xa7, 0x10, 0xdc, 0x07, 0xad, 0x15, 0x8a, 0xc7, 0x24, 0xf0, 0x06,
	0x8a, 0x83, 0x9c, 0x34, 0xd8, 0xd9, 0xca, 0x6c, 0xea, 0x26, 0x03, 0x5a, 0x28, 0x7d, 0xc7, 0xa7,
	0x48, 0xc1, 0x9a, 0xc1, 0x9f, 0x11, 0xef, 0x60, 0xa9, 0x74, 0xa4, 0xd8, 0x45, 0x61, 0x3b, 0x5f,
	0x99, 0x4d, 0xd5, 0x4c, 0x02, 0x6f, 0x61, 0xf9, 0x43, 0xf4, 0xf9, 0xde, 0xf1, 0x5e, 0xec, 0x62,
	0x78, 0x59, 0x25, 0xf1, 0xc2, 0x7b, 0x59, 0xff, 0xce, 0xa0, 0x7a, 0xed, 0xb9, 0x7d, 0xeb, 0x3c,
	0x21, 0xc2, 0xa2, 0x27, 0xa7, 0x63, 0xec, 0x30, 0xa7, 0x5d, 0xbc, 0x70, 0x3c, 0x8c, 0x99, 0x19,
	0xf0, 0x1a, 0xe6, 0x3b, 0xd7, 0x0f, 0x59, 0x75, 0x93, 0xc6, 0xb4, 0x5d, 0xfa, 0x34, 0xd9, 0x9c,
	0x71, 0xc6, 0xa9, 0x4d, 0x71, 0xa1, 0xcd, 0xd5, 0xff, 0x36, 0x16, 0xca, 0x40, 0xad, 0xf0, 0x2e,
	0xd8, 0x32, 0xdf, 0x8c, 0xf8, 0x64, 0x9e, 0xcd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xe7,
	0x38, 0xb0, 0x55, 0x01, 0x00, 0x00,
}
