// Code generated by protoc-gen-go.
// source: common/server/away_mode/away_mode.proto
// DO NOT EDIT!

/*
Package away_mode_message is a generated protocol buffer package.

It is generated from these files:
	common/server/away_mode/away_mode.proto

It has these top-level messages:
	LeaveHomeMessage
*/
package awaymode

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LeaveHomeMessage struct {
	StartHours       *uint32 `protobuf:"varint,1,req,name=startHours" json:"startHours,omitempty"`
	StartMinutes     *uint32 `protobuf:"varint,2,req,name=startMinutes" json:"startMinutes,omitempty"`
	FinishHours      *uint32 `protobuf:"varint,3,req,name=finishHours" json:"finishHours,omitempty"`
	FinishMinutes    *uint32 `protobuf:"varint,4,req,name=finishMinutes" json:"finishMinutes,omitempty"`
	Repetiton        *bool   `protobuf:"varint,5,req,name=repetiton" json:"repetiton,omitempty"`
	WeekInfo         *uint32 `protobuf:"varint,6,req,name=week_info,json=weekInfo" json:"week_info,omitempty"`
	LeaveHomeState   *bool   `protobuf:"varint,7,req,name=LeaveHomeState" json:"LeaveHomeState,omitempty"`
	LeaveMode        *uint32 `protobuf:"varint,8,opt,name=leaveMode" json:"leaveMode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LeaveHomeMessage) Reset()                    { *m = LeaveHomeMessage{} }
func (m *LeaveHomeMessage) String() string            { return proto.CompactTextString(m) }
func (*LeaveHomeMessage) ProtoMessage()               {}
func (*LeaveHomeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LeaveHomeMessage) GetStartHours() uint32 {
	if m != nil && m.StartHours != nil {
		return *m.StartHours
	}
	return 0
}

func (m *LeaveHomeMessage) GetStartMinutes() uint32 {
	if m != nil && m.StartMinutes != nil {
		return *m.StartMinutes
	}
	return 0
}

func (m *LeaveHomeMessage) GetFinishHours() uint32 {
	if m != nil && m.FinishHours != nil {
		return *m.FinishHours
	}
	return 0
}

func (m *LeaveHomeMessage) GetFinishMinutes() uint32 {
	if m != nil && m.FinishMinutes != nil {
		return *m.FinishMinutes
	}
	return 0
}

func (m *LeaveHomeMessage) GetRepetiton() bool {
	if m != nil && m.Repetiton != nil {
		return *m.Repetiton
	}
	return false
}

func (m *LeaveHomeMessage) GetWeekInfo() uint32 {
	if m != nil && m.WeekInfo != nil {
		return *m.WeekInfo
	}
	return 0
}

func (m *LeaveHomeMessage) GetLeaveHomeState() bool {
	if m != nil && m.LeaveHomeState != nil {
		return *m.LeaveHomeState
	}
	return false
}

func (m *LeaveHomeMessage) GetLeaveMode() uint32 {
	if m != nil && m.LeaveMode != nil {
		return *m.LeaveMode
	}
	return 0
}

func init() {
	proto.RegisterType((*LeaveHomeMessage)(nil), "away_mode.message.LeaveHomeMessage")
}

func init() { proto.RegisterFile("common/server/away_mode/away_mode.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xcf, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x06, 0x70, 0x1a, 0xff, 0x6d, 0x47, 0x57, 0x74, 0x4e, 0x01, 0x45, 0x96, 0x22, 0xba, 0x27,
	0xfb, 0x0e, 0x9e, 0x56, 0x70, 0x2f, 0xeb, 0x03, 0x94, 0x60, 0x67, 0x35, 0x68, 0x32, 0x25, 0x99,
	0xb6, 0xf8, 0x34, 0xbe, 0xaa, 0x6c, 0x16, 0x4d, 0xeb, 0x2d, 0xf3, 0xe3, 0x9b, 0x2f, 0x0c, 0xdc,
	0xbf, 0xb2, 0x73, 0xec, 0xe7, 0x91, 0xc2, 0x86, 0xc2, 0xdc, 0x6c, 0xcd, 0xd7, 0xc2, 0xf1, 0x92,
	0xf2, 0xeb, 0x61, 0x15, 0x58, 0x18, 0x2f, 0x33, 0x38, 0x8a, 0xd1, 0xbc, 0xd1, 0xec, 0x5b, 0xc1,
	0xc5, 0x33, 0x99, 0x0d, 0x35, 0xec, 0xa8, 0x1d, 0x11, 0x6f, 0x00, 0xa2, 0x98, 0x20, 0x0d, 0xaf,
	0x43, 0xd4, 0x93, 0x4a, 0xd5, 0x65, 0xb7, 0x23, 0x38, 0x83, 0xb3, 0x34, 0xb5, 0xd6, 0xaf, 0x85,
	0xa2, 0x56, 0x29, 0xb1, 0x67, 0x58, 0xc1, 0x69, 0x6f, 0xbd, 0x8d, 0xef, 0x63, 0xc9, 0x41, 0x8a,
	0xec, 0x12, 0xde, 0x42, 0x39, 0x8e, 0xbf, 0x35, 0x87, 0x29, 0xb3, 0x8f, 0x78, 0x0d, 0xd3, 0x40,
	0x2b, 0x12, 0x2b, 0xec, 0xf5, 0x51, 0xa5, 0xea, 0xa2, 0xcb, 0x80, 0x57, 0x30, 0xdd, 0x12, 0x7d,
	0x2c, 0xac, 0xef, 0x59, 0x1f, 0xa7, 0xfd, 0x62, 0x80, 0x27, 0xdf, 0x33, 0xde, 0xc1, 0xf9, 0xdf,
	0x69, 0x2f, 0x62, 0x84, 0xf4, 0x49, 0xda, 0xff, 0xa7, 0xc3, 0x17, 0x9f, 0x83, 0xb4, 0xbc, 0x24,
	0x5d, 0x54, 0x93, 0xba, 0xec, 0x32, 0x3c, 0xaa, 0x46, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb8,
	0x2d, 0x5e, 0xd8, 0x62, 0x01, 0x00, 0x00,
}
