// Code generated by protoc-gen-go.
// source: Light/Light_Event/Light_Event.proto
// DO NOT EDIT!

/*
Package Light_Event_message is a generated protocol buffer package.

It is generated from these files:
	Light/Light_Event/Light_Event.proto

It has these top-level messages:
	LampLightRgbCtlMessage
	LampLightLevelCtlMessage
*/
package lightevent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LampLightRgbCtlMessage struct {
	Red              *uint32 `protobuf:"varint,1,req,name=red" json:"red,omitempty"`
	Green            *uint32 `protobuf:"varint,2,req,name=green" json:"green,omitempty"`
	Blue             *uint32 `protobuf:"varint,3,req,name=blue" json:"blue,omitempty"`
	White            *uint32 `protobuf:"varint,4,opt,name=white" json:"white,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LampLightRgbCtlMessage) Reset()                    { *m = LampLightRgbCtlMessage{} }
func (m *LampLightRgbCtlMessage) String() string            { return proto.CompactTextString(m) }
func (*LampLightRgbCtlMessage) ProtoMessage()               {}
func (*LampLightRgbCtlMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LampLightRgbCtlMessage) GetRed() uint32 {
	if m != nil && m.Red != nil {
		return *m.Red
	}
	return 0
}

func (m *LampLightRgbCtlMessage) GetGreen() uint32 {
	if m != nil && m.Green != nil {
		return *m.Green
	}
	return 0
}

func (m *LampLightRgbCtlMessage) GetBlue() uint32 {
	if m != nil && m.Blue != nil {
		return *m.Blue
	}
	return 0
}

func (m *LampLightRgbCtlMessage) GetWhite() uint32 {
	if m != nil && m.White != nil {
		return *m.White
	}
	return 0
}

type LampLightLevelCtlMessage struct {
	Lum              *uint32 `protobuf:"varint,1,req,name=lum" json:"lum,omitempty"`
	ColorTemp        *uint32 `protobuf:"varint,2,opt,name=colorTemp" json:"colorTemp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LampLightLevelCtlMessage) Reset()                    { *m = LampLightLevelCtlMessage{} }
func (m *LampLightLevelCtlMessage) String() string            { return proto.CompactTextString(m) }
func (*LampLightLevelCtlMessage) ProtoMessage()               {}
func (*LampLightLevelCtlMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LampLightLevelCtlMessage) GetLum() uint32 {
	if m != nil && m.Lum != nil {
		return *m.Lum
	}
	return 0
}

func (m *LampLightLevelCtlMessage) GetColorTemp() uint32 {
	if m != nil && m.ColorTemp != nil {
		return *m.ColorTemp
	}
	return 0
}

func init() {
	proto.RegisterType((*LampLightRgbCtlMessage)(nil), "Light_Event.message.LampLightRgbCtlMessage")
	proto.RegisterType((*LampLightLevelCtlMessage)(nil), "Light_Event.message.LampLightLevelCtlMessage")
}

func init() { proto.RegisterFile("Light/Light_Event/Light_Event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xf6, 0xc9, 0x4c, 0xcf,
	0x28, 0xd1, 0x07, 0x93, 0xf1, 0xae, 0x65, 0xa9, 0x79, 0x28, 0x6c, 0xbd, 0x82, 0xa2, 0xfc, 0x92,
	0x7c, 0x21, 0x61, 0x64, 0xa1, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0xa5, 0x2c, 0x2e, 0x31,
	0x9f, 0xc4, 0xdc, 0x02, 0xb0, 0x54, 0x50, 0x7a, 0x92, 0x73, 0x49, 0x8e, 0x2f, 0x44, 0x46, 0x48,
	0x80, 0x8b, 0xb9, 0x28, 0x35, 0x45, 0x82, 0x51, 0x81, 0x49, 0x83, 0x37, 0x08, 0xc4, 0x14, 0x12,
	0xe1, 0x62, 0x4d, 0x2f, 0x4a, 0x4d, 0xcd, 0x93, 0x60, 0x02, 0x8b, 0x41, 0x38, 0x42, 0x42, 0x5c,
	0x2c, 0x49, 0x39, 0xa5, 0xa9, 0x12, 0xcc, 0x60, 0x41, 0x30, 0x1b, 0xa4, 0xb2, 0x3c, 0x23, 0xb3,
	0x24, 0x55, 0x82, 0x45, 0x81, 0x11, 0xa4, 0x12, 0xcc, 0x51, 0xf2, 0xe2, 0x92, 0x80, 0xdb, 0xe5,
	0x93, 0x5a, 0x96, 0x9a, 0x83, 0x6a, 0x5b, 0x4e, 0x69, 0x2e, 0xcc, 0xb6, 0x9c, 0xd2, 0x5c, 0x21,
	0x19, 0x2e, 0xce, 0xe4, 0xfc, 0x9c, 0xfc, 0xa2, 0x90, 0xd4, 0xdc, 0x02, 0x09, 0x26, 0xb0, 0x39,
	0x08, 0x01, 0x27, 0x26, 0x0f, 0x26, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x51, 0x3e, 0x6e, 0x66,
	0xf6, 0x00, 0x00, 0x00,
}
