// Code generated by protoc-gen-go.
// source: pbexample.proto
// DO NOT EDIT!

/*
Package pbexample is a generated protocol buffer package.

It is generated from these files:
	pbexample.proto

It has these top-level messages:
	Person
	Food
	House
*/
package pbexample

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) Enum() *Person_PhoneType {
	p := new(Person_PhoneType)
	*p = x
	return p
}
func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (x *Person_PhoneType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Person_PhoneType_value, data, "Person_PhoneType")
	if err != nil {
		return err
	}
	*x = Person_PhoneType(value)
	return nil
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name  *string               `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Id    *int32                `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Email *string               `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phone" json:"phone,omitempty"`
	MyMap map[string]string     `protobuf:"bytes,5,rep,name=myMap" json:"myMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Choice:
	//	*Person_Eat
	//	*Person_Live
	//	*Person_Others
	Choice           isPerson_Choice `protobuf_oneof:"choice"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isPerson_Choice interface {
	isPerson_Choice()
}

type Person_Eat struct {
	Eat *Food `protobuf:"bytes,6,opt,name=eat,oneof"`
}
type Person_Live struct {
	Live *House `protobuf:"bytes,7,opt,name=live,oneof"`
}
type Person_Others struct {
	Others string `protobuf:"bytes,8,opt,name=others,oneof"`
}

func (*Person_Eat) isPerson_Choice()    {}
func (*Person_Live) isPerson_Choice()   {}
func (*Person_Others) isPerson_Choice() {}

func (m *Person) GetChoice() isPerson_Choice {
	if m != nil {
		return m.Choice
	}
	return nil
}

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *Person) GetPhone() []*Person_PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *Person) GetMyMap() map[string]string {
	if m != nil {
		return m.MyMap
	}
	return nil
}

func (m *Person) GetEat() *Food {
	if x, ok := m.GetChoice().(*Person_Eat); ok {
		return x.Eat
	}
	return nil
}

func (m *Person) GetLive() *House {
	if x, ok := m.GetChoice().(*Person_Live); ok {
		return x.Live
	}
	return nil
}

func (m *Person) GetOthers() string {
	if x, ok := m.GetChoice().(*Person_Others); ok {
		return x.Others
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Person) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Person_OneofMarshaler, _Person_OneofUnmarshaler, _Person_OneofSizer, []interface{}{
		(*Person_Eat)(nil),
		(*Person_Live)(nil),
		(*Person_Others)(nil),
	}
}

func _Person_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Person)
	// choice
	switch x := m.Choice.(type) {
	case *Person_Eat:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Eat); err != nil {
			return err
		}
	case *Person_Live:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Live); err != nil {
			return err
		}
	case *Person_Others:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Others)
	case nil:
	default:
		return fmt.Errorf("Person.Choice has unexpected type %T", x)
	}
	return nil
}

func _Person_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Person)
	switch tag {
	case 6: // choice.eat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Food)
		err := b.DecodeMessage(msg)
		m.Choice = &Person_Eat{msg}
		return true, err
	case 7: // choice.live
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(House)
		err := b.DecodeMessage(msg)
		m.Choice = &Person_Live{msg}
		return true, err
	case 8: // choice.others
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Choice = &Person_Others{x}
		return true, err
	default:
		return false, nil
	}
}

func _Person_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Person)
	// choice
	switch x := m.Choice.(type) {
	case *Person_Eat:
		s := proto.Size(x.Eat)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Person_Live:
		s := proto.Size(x.Live)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Person_Others:
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Others)))
		n += len(x.Others)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Person_PhoneNumber struct {
	Number           *string           `protobuf:"bytes,1,req,name=number" json:"number,omitempty"`
	Type             *Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=Person_PhoneType,def=1" json:"type,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

const Default_Person_PhoneNumber_Type Person_PhoneType = Person_HOME

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Person_PhoneNumber_Type
}

type Food struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Price            *int32  `protobuf:"varint,2,req,name=price" json:"price,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Food) Reset()                    { *m = Food{} }
func (m *Food) String() string            { return proto.CompactTextString(m) }
func (*Food) ProtoMessage()               {}
func (*Food) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Food) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Food) GetPrice() int32 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

type House struct {
	Addr             *string `protobuf:"bytes,1,req,name=addr" json:"addr,omitempty"`
	Owner            *string `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *House) Reset()                    { *m = House{} }
func (m *House) String() string            { return proto.CompactTextString(m) }
func (*House) ProtoMessage()               {}
func (*House) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *House) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func (m *House) GetOwner() string {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "Person.PhoneNumber")
	proto.RegisterType((*Food)(nil), "Food")
	proto.RegisterType((*House)(nil), "House")
	proto.RegisterEnum("Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("pbexample.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x51, 0xcb, 0x9b, 0x30,
	0x14, 0xd5, 0x68, 0x5c, 0xbd, 0xc2, 0x37, 0x97, 0x7d, 0x8c, 0xac, 0xec, 0x41, 0x7c, 0x72, 0x14,
	0x64, 0xeb, 0x53, 0xe9, 0x63, 0xa1, 0xc3, 0xb1, 0xb9, 0x96, 0x30, 0x18, 0xec, 0xcd, 0xd6, 0x0b,
	0x95, 0xa9, 0x09, 0xd6, 0x76, 0xf3, 0x57, 0xed, 0x2f, 0x8e, 0x44, 0xdb, 0x6d, 0xf0, 0xbd, 0x9d,
	0x73, 0x3c, 0xb9, 0x9e, 0x7b, 0x12, 0x78, 0xae, 0x0e, 0xf8, 0xab, 0x68, 0x54, 0x8d, 0xa9, 0xea,
	0x64, 0x2f, 0xe3, 0xdf, 0x0e, 0x78, 0x7b, 0xec, 0xce, 0xb2, 0x65, 0x0c, 0xdc, 0xb6, 0x68, 0x90,
	0xdb, 0x11, 0x49, 0x7c, 0x61, 0x30, 0x7b, 0x00, 0x52, 0x95, 0x9c, 0x44, 0x24, 0xa1, 0x82, 0x54,
	0x25, 0x7b, 0x04, 0x8a, 0x4d, 0x51, 0xd5, 0xdc, 0x89, 0xec, 0xc4, 0x17, 0x23, 0x61, 0x6f, 0x81,
	0xaa, 0x93, 0x6c, 0x91, 0xbb, 0x91, 0x93, 0x04, 0xcb, 0x97, 0xe9, 0x38, 0x31, 0xdd, 0x6b, 0xf1,
	0xcb, 0xa5, 0x39, 0x60, 0x27, 0x46, 0x07, 0x4b, 0x80, 0x36, 0x43, 0x5e, 0x28, 0x4e, 0x8d, 0x95,
	0xdd, 0xac, 0xb9, 0x16, 0xb7, 0x6d, 0xdf, 0x0d, 0x62, 0x34, 0xb0, 0xd7, 0xe0, 0x60, 0xd1, 0x73,
	0x2f, 0xb2, 0x93, 0x60, 0x49, 0xd3, 0x0f, 0x52, 0x96, 0x99, 0x25, 0xb4, 0xc6, 0xde, 0x80, 0x5b,
	0x57, 0x57, 0xe4, 0xcf, 0xcc, 0x37, 0x2f, 0xcd, 0xe4, 0xe5, 0x8c, 0x99, 0x25, 0x8c, 0xca, 0x38,
	0x78, 0xb2, 0x3f, 0x61, 0x77, 0xe6, 0x33, 0x1d, 0x32, 0xb3, 0xc4, 0xc4, 0xe7, 0x02, 0x82, 0x7f,
	0x22, 0xb1, 0x57, 0xe0, 0xb5, 0x06, 0x4d, 0x2b, 0x4f, 0x8c, 0x2d, 0xc0, 0xed, 0x07, 0x85, 0x9c,
	0x44, 0x76, 0xf2, 0xb0, 0x7c, 0xf1, 0xdf, 0x36, 0x5f, 0x07, 0x85, 0x6b, 0x37, 0xdb, 0xe5, 0x5b,
	0x61, 0x4c, 0xf3, 0x15, 0xc0, 0xdf, 0xec, 0x2c, 0x04, 0xe7, 0x07, 0x0e, 0xdc, 0x36, 0xed, 0x68,
	0xa8, 0x1b, 0xbb, 0x16, 0xf5, 0x65, 0x9c, 0xe6, 0x8b, 0x91, 0xac, 0xc9, 0xca, 0x8e, 0x17, 0xe0,
	0xdf, 0x47, 0x32, 0x00, 0x2f, 0xdf, 0x6d, 0x3e, 0x7e, 0xde, 0x86, 0x16, 0x9b, 0x81, 0xf9, 0x41,
	0x68, 0x6b, 0xf4, 0x6d, 0x27, 0x3e, 0x85, 0x64, 0x33, 0x03, 0xef, 0x78, 0x92, 0xd5, 0x11, 0xe3,
	0x77, 0xe0, 0xea, 0x2e, 0x9e, 0xbc, 0xae, 0x47, 0xa0, 0xaa, 0xab, 0x8e, 0x38, 0xdd, 0xd8, 0x48,
	0xe2, 0xf7, 0x40, 0x4d, 0x43, 0xfa, 0x48, 0x51, 0x96, 0xb7, 0x75, 0x0d, 0xd6, 0x47, 0xe4, 0xcf,
	0x16, 0xbb, 0x5b, 0x3e, 0x43, 0x36, 0xc1, 0x77, 0xff, 0xfe, 0x52, 0xfe, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xe9, 0x74, 0x5f, 0xfb, 0x35, 0x02, 0x00, 0x00,
}
